name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
